# Site settings
title: "Sysadmin Notebook"
description: "Minimalist Jekyll theme for documentation site"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://spencerriner.github.io"
author: "Spencer Riner"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
